---
title: "Associative Classification Software"
date: 'Report date: `r format.Date(Sys.Date(),"%m/%d/%Y")`'
output:
  word_document: default
  html_document:
    df_print: tibble
always_allow_html: yes
---

## Parameters

```{r, echo=FALSE}

DT::datatable(parameters(),rownames = FALSE,
          options = list(paging = FALSE,ordering=FALSE,
                         searching=FALSE, autoWidth = TRUE,info=FALSE,scrollX=FALSE,
                         columnDefs = list(list(className = "dt-center",targets = "_all")),
                         initComplete = DT::JS("function(settings, json) {",
                                           "$(this.api().table().header()).css({'background-color': '#18bc9c', 'color': '#fff'});",
                                           "}")
                         #language = list(url = "//cdn.datatables.net/plug-ins/1.10.11/i18n/Turkish.json")
                         ),
          caption = tags$caption(
            style = 'caption-side: top; text-align: center;',
            tags$h5(strong("Table 1:"),"Parameters"))
          )

```

## Predictors

`r paste(used_predictors(),sep = ", ")`



## Classification results

```{r, echo=FALSE} 

sketch = htmltools::withTags(table(class = "display",thead(tr(th(rowspan = 2, "Prediction"),th(class = "dt-center",colspan = length(lev())+1, "Reference")),
                                                                     tr(lapply(c(lev(),"Total"), th)))))

DT::datatable(cm_table,rownames = FALSE,container = sketch,
          options = list(paging = FALSE,ordering=FALSE,
                         searching=FALSE, autoWidth = TRUE,info=FALSE,scrollX=FALSE,
                         columnDefs = list(list(className = "dt-center",targets = "_all")),
                         initComplete = DT::JS("function(settings, json) {",
                                           "$(this.api().table().header()).css({'background-color': '#18bc9c', 'color': '#fff'});",
                                           "}")
                         ),
          caption = tags$caption(
            style = 'caption-side: top; text-align: center;',
            tags$h5(strong("Table 2:"),"Confusion matrix"))
          )
```

```{r, echo=FALSE} 
DT::datatable(metrics_matrix,rownames = FALSE,
         options = list(paging = FALSE,ordering=TRUE,
                        searching=FALSE, autoWidth = TRUE,info=FALSE,scrollX=FALSE,
                        columnDefs = list(list(className = "dt-center",targets = "_all")),
                        initComplete = DT::JS("function(settings, json) {",
                                          "$(this.api().table().header()).css({'background-color': '#18bc9c', 'color': '#fff'});",
                                          "}")
                        ),
         caption = tags$caption(
           style = 'caption-side: top; text-align: center;',
           tags$h5(strong("Table 3:"),"Metrics related to the classification performance of the model"))
)
```

## Association rules

```{r, echo=FALSE} 

  rules_table=arules::DATAFRAME(model()$rules)[,c(1:4,7)]
  colnames(rules_table)=c("Left hand side rules","Right hand side rules","Support","Confidence","Frequency")
  k=NROW(rules_table)
  for (i in 1:k) {
    rules_table[i,3]=round(rules_table[i,3],3)
    rules_table[i,4]=round(rules_table[i,4],3)
    }
  
  DT::datatable(rules_table[,1:5],rownames = FALSE,
            options = list(paging = FALSE,ordering=TRUE,
                           searching=FALSE, autoWidth = TRUE,info=FALSE,scrollX=FALSE,
                           columnDefs = list(list(className = "dt-center",targets = "_all")),
                           initComplete = DT::JS("function(settings, json) {",
                                             "$(this.api().table().header()).css({'background-color': '#18bc9c', 'color': '#fff'});",
                                                     "}")
                           ),
            caption = tags$caption(
              style = 'caption-side: top; text-align: center;',
              tags$h5(strong("Table 4: "),"Association rules used by the classification algorithm"))
            )

```

## Network visualization of association rules

```{r, echo=FALSE,fig.height=12,fig.width=12,out.height="100%",out.width="100%"}

plt=arulesViz:::plot.rules(model()$rules, method = "graph",shading = "confidence", engine = "htmlwidget")
plt$sizingPolicy=htmlwidgets::sizingPolicy(viewer.paneHeight=1000,browser.defaultHeight=1000,knitr.defaultHeight=1000,defaultHeight=1000,defaultWidth=1000, browser.fill=TRUE)
plt$height=1000
plt$x$height=1000
plt


```